version: '3.8'

services:
  # Confluence MCP 服务器
  confluence-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: confluence-mcp-server
    restart: unless-stopped
    ports:
      - "8080:8080"  # SSE HTTP 接口端口
    environment:
      - NODE_ENV=production
      - PORT=8080
      - MCP_SERVER_NAME=confluence-mcp
      - MCP_SERVER_VERSION=1.0.0
      # Confluence API 配置（从 .env 文件或环境变量获取）
      - CONFLUENCE_BASE_URL=${CONFLUENCE_BASE_URL}
      - CONFLUENCE_API_TOKEN=${CONFLUENCE_API_TOKEN}
      - CONFLUENCE_USER_EMAIL=${CONFLUENCE_USER_EMAIL}
    volumes:
      - ./logs:/app/logs  # 日志目录
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mcp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  logs:
    driver: local